### ISSUE TITLE
Non-Issue: Hitbox Merged

### ISSUE THREAD

**Issue by eaaliprantis** [oyed/apinterface#1]
Hello,

I assume you are aware of the most recent merge between Hitbox and Azubu (https://www.smashcast.tv/).  Just letting you know.  Also, I would not mind working with you on this project. Because it looks as though it is a really awesome project.  And we both have similar goals. xD

**Comment by oyed** [comment]
Yes I'm aware - I have good communication with the Hitbox Team so when the time comes that they do something with their API I should be told about it.

And feel free to contribute! There are many interfaces which don't yet have full coverage of their respective API's. I just ask that you only change/add to 1 interface per PR.
